version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      MONGO_URI: "mongodb://localhost:27017/Users"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
